// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuiSNCF.Database;

#nullable disable

namespace QuiSNCF.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260611132330_indexex")]
    partial class indexex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuiSNCF.Models.DailyPlay", b =>
                {
                    b.Property<int>("DailyPlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DailyPlayId"));

                    b.Property<int>("GameType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PlayedDate")
                        .HasColumnType("date");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Tries")
                        .HasColumnType("integer");

                    b.HasKey("DailyPlayId");

                    b.HasIndex("PlayerId", "GameType", "PlayedDate")
                        .HasDatabaseName("IX_DailyPlays_PlayerId_GameType_PlayedDate");

                    b.ToTable("DailyPlays");
                });

            modelBuilder.Entity("QuiSNCF.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Tries")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Players_Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("QuiSNCF.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LastTimePlayed")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RandomX")
                        .HasColumnType("double precision");

                    b.Property<double>("RandomY")
                        .HasColumnType("double precision");

                    b.HasKey("StationId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("QuiSNCF.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WordId"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LastTimePlayed")
                        .HasColumnType("date");

                    b.Property<string>("WordName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WordId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("QuiSNCF.Models.DailyPlay", b =>
                {
                    b.HasOne("QuiSNCF.Models.Player", "Player")
                        .WithMany("DailyPlays")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("QuiSNCF.Models.Player", b =>
                {
                    b.Navigation("DailyPlays");
                });
#pragma warning restore 612, 618
        }
    }
}
