services:
  game-database:
    image: postgres:15
    container_name: game-database
    env_file:
      - .env.docker.game
    volumes:
      - game-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_game_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  game-service:
    build: QuiSNCF/
    container_name: game-service
    env_file:
      - .env.docker.game
    ports:
      - "4010:4010"
    depends_on:
      game-database:
        condition: service_healthy

volumes:
  game-database:
